In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
prev_app_df=pd.read_csv(r"D:\Projects\Trainity\loan\previous_application.csv")

In [3]:
prev_app_df

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

In [4]:
prev_app_df.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL'],
      dtype='object')

## We need to find driver variables that causes loan default i.e., factors that affect loan repayment

## Variables with most null values cannot be a driving factor hence we need to romve those columns

In [5]:
null_prev_app_df=pd.DataFrame(round((prev_app_df.isnull().sum()/prev_app_df.shape[0])*100,2)).reset_index()

In [6]:
null_prev_app_df.columns=['column_name','null_values_percent']

In [7]:
null_prev_app_df

                    column_name  null_values_percent
0                    SK_ID_PREV                 0.00
1                    SK_ID_CURR                 0.00
2            NAME_CONTRACT_TYPE                 0.00
3                   AMT_ANNUITY                22.29
4               AMT_APPLICATION                 0.00
5                    AMT_CREDIT                 0.00
6              AMT_DOWN_PAYMENT                53.64
7               AMT_GOODS_PRICE                23.08
8    WEEKDAY_APPR_PROCESS_START                 0.00
9       HOUR_APPR_PROCESS_START                 0.00
10  FLAG_LAST_APPL_PER_CONTRACT                 0.00
11       NFLAG_LAST_APPL_IN_DAY                 0.00
12            RATE_DOWN_PAYMENT                53.64
13        RATE_INTEREST_PRIMARY                99.64
14     RATE_INTEREST_PRIVILEGED                99.64
15       NAME_CASH_LOAN_PURPOSE                 0.00
16         NAME_CONTRACT_STATUS                 0.00
17                DAYS_DECISION                 0.00
18            NAME_PAYMENT_TYPE                 0.00
19           CODE_REJECT_REASON                 0.00
20              NAME_TYPE_SUITE                49.12
21             NAME_CLIENT_TYPE                 0.00
22          NAME_GOODS_CATEGORY                 0.00
23               NAME_PORTFOLIO                 0.00
24            NAME_PRODUCT_TYPE                 0.00
25                 CHANNEL_TYPE                 0.00
26             SELLERPLACE_AREA                 0.00
27         NAME_SELLER_INDUSTRY                 0.00
28                  CNT_PAYMENT                22.29
29             NAME_YIELD_GROUP                 0.00
30          PRODUCT_COMBINATION                 0.02
31           DAYS_FIRST_DRAWING                40.30
32               DAYS_FIRST_DUE                40.30
33    DAYS_LAST_DUE_1ST_VERSION                40.30
34                DAYS_LAST_DUE                40.30
35             DAYS_TERMINATION                40.30
36    NFLAG_INSURED_ON_APPROVAL                40.30

In [8]:
null_prev_app_df_10=null_prev_app_df[null_prev_app_df["null_values_percent"]>10]

In [9]:
null_prev_app_df_10["column_name"].shape

(14,)

In [10]:
s=null_prev_app_df_10["column_name"]
arr = s.to_numpy()

print(arr)

['AMT_ANNUITY' 'AMT_DOWN_PAYMENT' 'AMT_GOODS_PRICE' 'RATE_DOWN_PAYMENT'
 'RATE_INTEREST_PRIMARY' 'RATE_INTEREST_PRIVILEGED' 'NAME_TYPE_SUITE'
 'CNT_PAYMENT' 'DAYS_FIRST_DRAWING' 'DAYS_FIRST_DUE'
 'DAYS_LAST_DUE_1ST_VERSION' 'DAYS_LAST_DUE' 'DAYS_TERMINATION'
 'NFLAG_INSURED_ON_APPROVAL']

In [11]:
prev_app_df2=prev_app_df

In [12]:
prev_app_df2 = prev_app_df2.drop(arr, axis=1)

In [13]:
prev_app_df2

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_APPLICATION,AMT_CREDIT,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,NAME_CASH_LOAN_PURPOSE,...,CODE_REJECT_REASON,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,NAME_YIELD_GROUP,PRODUCT_COMBINATION
0,2030495,271877,Consumer loans,17145.0,17145.0,SATURDAY,15,Y,1,XAP,...,XAP,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,middle,POS mobile with interest
1,2802425,108129,Cash loans,607500.0,679671.0,THURSDAY,11,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,low_action,Cash X-Sell: low
2,2523466,122040,Cash loans,112500.0,136444.5,TUESDAY,11,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,high,Cash X-Sell: high
3,2819243,176158,Cash loans,450000.0,470790.0,MONDAY,7,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,middle,Cash X-Sell: middle
4,1784265,202054,Cash loans,337500.0,404055.0,THURSDAY,9,Y,1,Repairs,...,HC,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,high,Cash Street: high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,267295.5,311400.0,WEDNESDAY,12,Y,1,XAP,...,XAP,Refreshed,Furniture,POS,XNA,Stone,43,Furniture,low_normal,POS industry with interest
1670210,2357031,334635,Consumer loans,87750.0,64291.5,TUESDAY,15,Y,1,XAP,...,XAP,New,Furniture,POS,XNA,Stone,43,Furniture,middle,POS industry with interest
1670211,2659632,249544,Consumer loans,105237.0,102523.5,MONDAY,12,Y,1,XAP,...,XAP,Repeater,Consumer Electronics,POS,XNA,Country-wide,1370,Consumer electronics,low_normal,POS household with interest
1670212,2785582,400317,Cash loans,180000.0,191880.0,WEDNESDAY,9,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,AP+ (Cash loan),-1,XNA,low_normal,Cash X-Sell: low
1670213,2418762,261212,Cash loans,360000.0,360000.0,SUNDAY,10,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,AP+ (Cash loan),-1,XNA,middle,Cash X-Sell: middle

In [14]:
prev_app_df2.duplicated().sum()

0

In [15]:
prev_app_df_clean = prev_app_df2.dropna()

In [16]:
prev_app_df_clean.isnull().sum()

SK_ID_PREV                     0
SK_ID_CURR                     0
NAME_CONTRACT_TYPE             0
AMT_APPLICATION                0
AMT_CREDIT                     0
WEEKDAY_APPR_PROCESS_START     0
HOUR_APPR_PROCESS_START        0
FLAG_LAST_APPL_PER_CONTRACT    0
NFLAG_LAST_APPL_IN_DAY         0
NAME_CASH_LOAN_PURPOSE         0
NAME_CONTRACT_STATUS           0
DAYS_DECISION                  0
NAME_PAYMENT_TYPE              0
CODE_REJECT_REASON             0
NAME_CLIENT_TYPE               0
NAME_GOODS_CATEGORY            0
NAME_PORTFOLIO                 0
NAME_PRODUCT_TYPE              0
CHANNEL_TYPE                   0
SELLERPLACE_AREA               0
NAME_SELLER_INDUSTRY           0
NAME_YIELD_GROUP               0
PRODUCT_COMBINATION            0
dtype: int64

In [17]:
prev_app_df_clean

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_APPLICATION,AMT_CREDIT,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,NAME_CASH_LOAN_PURPOSE,...,CODE_REJECT_REASON,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,NAME_YIELD_GROUP,PRODUCT_COMBINATION
0,2030495,271877,Consumer loans,17145.0,17145.0,SATURDAY,15,Y,1,XAP,...,XAP,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,middle,POS mobile with interest
1,2802425,108129,Cash loans,607500.0,679671.0,THURSDAY,11,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,low_action,Cash X-Sell: low
2,2523466,122040,Cash loans,112500.0,136444.5,TUESDAY,11,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,high,Cash X-Sell: high
3,2819243,176158,Cash loans,450000.0,470790.0,MONDAY,7,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,middle,Cash X-Sell: middle
4,1784265,202054,Cash loans,337500.0,404055.0,THURSDAY,9,Y,1,Repairs,...,HC,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,high,Cash Street: high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,267295.5,311400.0,WEDNESDAY,12,Y,1,XAP,...,XAP,Refreshed,Furniture,POS,XNA,Stone,43,Furniture,low_normal,POS industry with interest
1670210,2357031,334635,Consumer loans,87750.0,64291.5,TUESDAY,15,Y,1,XAP,...,XAP,New,Furniture,POS,XNA,Stone,43,Furniture,middle,POS industry with interest
1670211,2659632,249544,Consumer loans,105237.0,102523.5,MONDAY,12,Y,1,XAP,...,XAP,Repeater,Consumer Electronics,POS,XNA,Country-wide,1370,Consumer electronics,low_normal,POS household with interest
1670212,2785582,400317,Cash loans,180000.0,191880.0,WEDNESDAY,9,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,AP+ (Cash loan),-1,XNA,low_normal,Cash X-Sell: low
1670213,2418762,261212,Cash loans,360000.0,360000.0,SUNDAY,10,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,AP+ (Cash loan),-1,XNA,middle,Cash X-Sell: middle

In [18]:
num_rows = int(len(prev_app_df_clean) * 0.50)

# Extract 50% of the data into a new DataFrame
df_sample = prev_app_df_clean.sample(n=num_rows, random_state=42)

# Save the extracted data to a new Excel sheet

In [19]:
df_sample

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_APPLICATION,AMT_CREDIT,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,NAME_CASH_LOAN_PURPOSE,...,CODE_REJECT_REASON,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,NAME_YIELD_GROUP,PRODUCT_COMBINATION
1602583,1820696,110636,Revolving loans,0.0,0.0,SUNDAY,9,Y,1,XAP,...,XAP,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,XNA,Card Street
665945,1260909,232322,Consumer loans,37705.5,36985.5,FRIDAY,12,Y,1,XAP,...,XAP,New,Mobile,POS,XNA,Country-wide,26,Connectivity,low_normal,POS mobile with interest
321310,2262505,118531,Consumer loans,21375.0,21433.5,SUNDAY,12,Y,1,XAP,...,XAP,New,Mobile,POS,XNA,Country-wide,45,Connectivity,high,POS mobile with interest
826919,1066145,163394,Cash loans,315000.0,364459.5,SUNDAY,13,Y,1,Other,...,LIMIT,Refreshed,XNA,Cash,walk-in,AP+ (Cash loan),5,XNA,high,Cash Street: high
818576,1805515,453641,Revolving loans,0.0,450000.0,FRIDAY,9,N,1,XAP,...,HC,Repeater,XNA,Cards,x-sell,Credit and cash offices,-1,XNA,XNA,Card X-Sell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467076,1870325,395756,Cash loans,225000.0,247275.0,MONDAY,12,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Country-wide,50,Consumer electronics,middle,Cash Street: middle
1030040,1915034,328463,Consumer loans,74781.0,37390.5,MONDAY,15,Y,1,XAP,...,XAP,New,Computers,POS,XNA,Country-wide,50,Connectivity,high,POS mobile without interest
1638380,2339381,370946,Revolving loans,45000.0,45000.0,MONDAY,10,Y,1,XAP,...,HC,Repeater,XNA,Cards,walk-in,Stone,265,Consumer electronics,XNA,Card Street
143265,2583544,330017,Cash loans,450000.0,450000.0,THURSDAY,9,Y,1,XNA,...,XAP,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,middle,Cash X-Sell: middle
1135246,1646051,354865,Consumer loans,117490.5,117490.5,WEDNESDAY,7,Y,1,XAP,...,SCO,Repeater,Computers,POS,XNA,Stone,60,Consumer electronics,low_normal,POS household with interest

df_sample.to_excel('previous_new_app.xlsx', index=False)